name: Lint

on:
    push:

env:
    NODE_VERSION: 16

jobs:
    lint:
        name: Run linters and tsc
        runs-on: ubuntu-20.04
        steps:
            - name: Install NodeJS
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ env.NODE_VERSION }}
                  cache: "yarn"

            - name: Code Checkout
              uses: actions/checkout@v2

            - run: yarn install --frozen-lockfile --ignore-scripts
            - run: yarn run lint
            - run: yarn run type-check
